# Generated by Django 3.2.2 on 2021-07-12 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'cards',
            },
        ),
        migrations.CreateModel(
            name='Decks',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'decks',
            },
        ),
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブフラグ')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'labs',
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_no', models.SmallIntegerField(blank=True, null=True, verbose_name='カード内番号')),
                ('is_main_recode', models.BooleanField(default=False, verbose_name='メインレコードフラグ')),
                ('file_name', models.CharField(max_length=50, verbose_name='ファイル名')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lab.cards', verbose_name='Card ID')),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lab.decks', verbose_name='Deck ID')),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lab.labs', verbose_name='Lab ID')),
            ],
            options={
                'db_table': 'records',
            },
        ),
        migrations.AddField(
            model_name='decks',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lab.labs', verbose_name='Lab ID'),
        ),
        migrations.AddField(
            model_name='cards',
            name='deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lab.decks', verbose_name='Deck ID'),
        ),
        migrations.AddField(
            model_name='cards',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lab.labs', verbose_name='Lab ID'),
        ),
    ]
