# Generated by Django 3.2.2 on 2021-06-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, verbose_name='ログインID')),
                ('password', models.CharField(max_length=255, verbose_name='パスワード')),
                ('name', models.TextField(verbose_name='表示ユーザ名')),
                ('mail', models.CharField(max_length=255, verbose_name='メールアドレス')),
                ('auth', models.CharField(max_length=1, verbose_name='権限')),
                ('status', models.CharField(max_length=1, verbose_name='アカウントステータス')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ユーザー情報',
                'db_table': 'Users',
                'ordering': ['id'],
            },
        ),
    ]
